version: '3.9'

networks:
  balance-api:

volumes:
  pgdata:

services:
  balance-api:
    container_name: balance-api
    build: ./
    volumes:
      - ./:/go/src/app
    environment:
      POSTGRES_HOST: balance-db
      POSTGRES_PORT: 5432
    command:
      - /bin/sh
      - -c
      - |
        ./cmd/app/wait-for-postgres.sh -h balance-db -u ${POSTGRES_USER} -p ${POSTGRES_PASSWORD} -d ${POSTGRES_DB} -c "migrate -path ./internal/store/pg/migrations -database postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@balance-db:5432/${POSTGRES_DB}?sslmode=${POSTGRES_SSL_MODE} up"
        ./balance-api
    ports:
      - "${HTTP_PORT}:8080"
    depends_on:
      - balance-db
    networks:
      - balance-api

  balance-db:
    container_name: balance-db
    image: postgres:13-alpine
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: ${WORKSPACE_TIMEZONE}
      PGDATA: /var/lib/postgresql/data/pgdata/
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - balance-api