version: '3.9'

networks:
  customer-api:

volumes:
  pgdata:

services:
  api:
    container_name: customer-api
    build: ./
    volumes:
      - ./:/go/src/app
    command: ./cmd/wait-for-postgres.sh -h db -u ${POSTGRES_USER} -p ${POSTGRES_PASSWORD} -d ${POSTGRES_DB} -c ./customer-api
    ports:
      - "${API_PORT}:8080"
    depends_on:
      - db
    networks:
      - customer-api

  db:
    container_name: customer-db
    image: postgres:13-alpine
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: ${WORKSPACE_TIMEZONE}
      PGDATA: /var/lib/postgresql/data/pgdata/
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - customer-api